import requests
import json
import os
from dotenv import load_dotenv

with open("code.py") as f:
    file = f.read()

load_dotenv()
key = os.getenv("KEY")
if key is None:
    raise ValueError("No key")

response = requests.post(
  url="https://api.typesafe.ai/v1/systemone",
  headers={
    "Authorization": f"Bearer {key}",
    "Content-Type": "application/json"
  },
  data=json.dumps(
{
    "model": "jev-latest",
    "state": file,
    "questions": {
        "is_totally_by_ai": {
            "type": "noul",
            "instructions": "This code was generated by AI. Code that has been coded or written by AI is characterized by obvious elements, such as overly specific and unnecessary comments, text that is too well-written, emojis, and the “—” character.",
            "criteria": {
                "true": "This code was generated by an ia",
                "false": "All this code is write by an human"
            }
        },
        "is_assisted_by_ai": {
            "type": "noul",
            "instructions": "This code contains sections generated by AI. Code that has been coded or written by AI is characterized by obvious elements, such as overly specific and unnecessary comments, text that is too well-written, emojis, and the “—” character.",
            "criteria": {
                "true": "This code was assisted by an ia and contain IA block",
                "false": "All this code is write by an human"
            }
        }
    }
})
)

answer = response.json()
print(answer)
